// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"module.resume/internal/infrastructure/persistence/gorm/model"
)

func newAward(db *gorm.DB, opts ...gen.DOOption) award {
	_award := award{}

	_award.awardDo.UseDB(db, opts...)
	_award.awardDo.UseModel(&model.Award{})

	tableName := _award.awardDo.TableName()
	_award.ALL = field.NewAsterisk(tableName)
	_award.ID = field.NewInt64(tableName, "id")
	_award.UsersID = field.NewInt64(tableName, "users_id")
	_award.Name = field.NewString(tableName, "name")
	_award.Issuer = field.NewString(tableName, "issuer")
	_award.AwardedDate = field.NewTime(tableName, "awarded_date")
	_award.Description = field.NewString(tableName, "description")
	_award.DeletedAt = field.NewField(tableName, "deleted_at")

	_award.fillFieldMap()

	return _award
}

type award struct {
	awardDo awardDo

	ALL         field.Asterisk
	ID          field.Int64
	UsersID     field.Int64
	Name        field.String
	Issuer      field.String
	AwardedDate field.Time
	Description field.String
	DeletedAt   field.Field

	fieldMap map[string]field.Expr
}

func (a award) Table(newTableName string) *award {
	a.awardDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a award) As(alias string) *award {
	a.awardDo.DO = *(a.awardDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *award) updateTableName(table string) *award {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.UsersID = field.NewInt64(table, "users_id")
	a.Name = field.NewString(table, "name")
	a.Issuer = field.NewString(table, "issuer")
	a.AwardedDate = field.NewTime(table, "awarded_date")
	a.Description = field.NewString(table, "description")
	a.DeletedAt = field.NewField(table, "deleted_at")

	a.fillFieldMap()

	return a
}

func (a *award) WithContext(ctx context.Context) *awardDo { return a.awardDo.WithContext(ctx) }

func (a award) TableName() string { return a.awardDo.TableName() }

func (a award) Alias() string { return a.awardDo.Alias() }

func (a award) Columns(cols ...field.Expr) gen.Columns { return a.awardDo.Columns(cols...) }

func (a *award) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *award) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 7)
	a.fieldMap["id"] = a.ID
	a.fieldMap["users_id"] = a.UsersID
	a.fieldMap["name"] = a.Name
	a.fieldMap["issuer"] = a.Issuer
	a.fieldMap["awarded_date"] = a.AwardedDate
	a.fieldMap["description"] = a.Description
	a.fieldMap["deleted_at"] = a.DeletedAt
}

func (a award) clone(db *gorm.DB) award {
	a.awardDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a award) replaceDB(db *gorm.DB) award {
	a.awardDo.ReplaceDB(db)
	return a
}

type awardDo struct{ gen.DO }

func (a awardDo) Debug() *awardDo {
	return a.withDO(a.DO.Debug())
}

func (a awardDo) WithContext(ctx context.Context) *awardDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a awardDo) ReadDB() *awardDo {
	return a.Clauses(dbresolver.Read)
}

func (a awardDo) WriteDB() *awardDo {
	return a.Clauses(dbresolver.Write)
}

func (a awardDo) Session(config *gorm.Session) *awardDo {
	return a.withDO(a.DO.Session(config))
}

func (a awardDo) Clauses(conds ...clause.Expression) *awardDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a awardDo) Returning(value interface{}, columns ...string) *awardDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a awardDo) Not(conds ...gen.Condition) *awardDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a awardDo) Or(conds ...gen.Condition) *awardDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a awardDo) Select(conds ...field.Expr) *awardDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a awardDo) Where(conds ...gen.Condition) *awardDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a awardDo) Order(conds ...field.Expr) *awardDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a awardDo) Distinct(cols ...field.Expr) *awardDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a awardDo) Omit(cols ...field.Expr) *awardDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a awardDo) Join(table schema.Tabler, on ...field.Expr) *awardDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a awardDo) LeftJoin(table schema.Tabler, on ...field.Expr) *awardDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a awardDo) RightJoin(table schema.Tabler, on ...field.Expr) *awardDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a awardDo) Group(cols ...field.Expr) *awardDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a awardDo) Having(conds ...gen.Condition) *awardDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a awardDo) Limit(limit int) *awardDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a awardDo) Offset(offset int) *awardDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a awardDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *awardDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a awardDo) Unscoped() *awardDo {
	return a.withDO(a.DO.Unscoped())
}

func (a awardDo) Create(values ...*model.Award) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a awardDo) CreateInBatches(values []*model.Award, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a awardDo) Save(values ...*model.Award) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a awardDo) First() (*model.Award, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Award), nil
	}
}

func (a awardDo) Take() (*model.Award, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Award), nil
	}
}

func (a awardDo) Last() (*model.Award, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Award), nil
	}
}

func (a awardDo) Find() ([]*model.Award, error) {
	result, err := a.DO.Find()
	return result.([]*model.Award), err
}

func (a awardDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Award, err error) {
	buf := make([]*model.Award, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a awardDo) FindInBatches(result *[]*model.Award, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a awardDo) Attrs(attrs ...field.AssignExpr) *awardDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a awardDo) Assign(attrs ...field.AssignExpr) *awardDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a awardDo) Joins(fields ...field.RelationField) *awardDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a awardDo) Preload(fields ...field.RelationField) *awardDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a awardDo) FirstOrInit() (*model.Award, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Award), nil
	}
}

func (a awardDo) FirstOrCreate() (*model.Award, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Award), nil
	}
}

func (a awardDo) FindByPage(offset int, limit int) (result []*model.Award, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a awardDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a awardDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a awardDo) Delete(models ...*model.Award) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *awardDo) withDO(do gen.Dao) *awardDo {
	a.DO = *do.(*gen.DO)
	return a
}
