// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"module.resume/internal/infrastructure/persistence/gorm/model"
)

func newCommonType(db *gorm.DB, opts ...gen.DOOption) commonType {
	_commonType := commonType{}

	_commonType.commonTypeDo.UseDB(db, opts...)
	_commonType.commonTypeDo.UseModel(&model.CommonType{})

	tableName := _commonType.commonTypeDo.TableName()
	_commonType.ALL = field.NewAsterisk(tableName)
	_commonType.ID = field.NewInt64(tableName, "id")
	_commonType.Domain = field.NewString(tableName, "domain")
	_commonType.Code = field.NewString(tableName, "code")
	_commonType.Name = field.NewString(tableName, "name")
	_commonType.Description = field.NewString(tableName, "description")
	_commonType.DeletedAt = field.NewField(tableName, "deleted_at")

	_commonType.fillFieldMap()

	return _commonType
}

type commonType struct {
	commonTypeDo commonTypeDo

	ALL         field.Asterisk
	ID          field.Int64
	Domain      field.String
	Code        field.String
	Name        field.String
	Description field.String
	DeletedAt   field.Field

	fieldMap map[string]field.Expr
}

func (c commonType) Table(newTableName string) *commonType {
	c.commonTypeDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c commonType) As(alias string) *commonType {
	c.commonTypeDo.DO = *(c.commonTypeDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *commonType) updateTableName(table string) *commonType {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.Domain = field.NewString(table, "domain")
	c.Code = field.NewString(table, "code")
	c.Name = field.NewString(table, "name")
	c.Description = field.NewString(table, "description")
	c.DeletedAt = field.NewField(table, "deleted_at")

	c.fillFieldMap()

	return c
}

func (c *commonType) WithContext(ctx context.Context) *commonTypeDo {
	return c.commonTypeDo.WithContext(ctx)
}

func (c commonType) TableName() string { return c.commonTypeDo.TableName() }

func (c commonType) Alias() string { return c.commonTypeDo.Alias() }

func (c commonType) Columns(cols ...field.Expr) gen.Columns { return c.commonTypeDo.Columns(cols...) }

func (c *commonType) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *commonType) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 6)
	c.fieldMap["id"] = c.ID
	c.fieldMap["domain"] = c.Domain
	c.fieldMap["code"] = c.Code
	c.fieldMap["name"] = c.Name
	c.fieldMap["description"] = c.Description
	c.fieldMap["deleted_at"] = c.DeletedAt
}

func (c commonType) clone(db *gorm.DB) commonType {
	c.commonTypeDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c commonType) replaceDB(db *gorm.DB) commonType {
	c.commonTypeDo.ReplaceDB(db)
	return c
}

type commonTypeDo struct{ gen.DO }

func (c commonTypeDo) Debug() *commonTypeDo {
	return c.withDO(c.DO.Debug())
}

func (c commonTypeDo) WithContext(ctx context.Context) *commonTypeDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c commonTypeDo) ReadDB() *commonTypeDo {
	return c.Clauses(dbresolver.Read)
}

func (c commonTypeDo) WriteDB() *commonTypeDo {
	return c.Clauses(dbresolver.Write)
}

func (c commonTypeDo) Session(config *gorm.Session) *commonTypeDo {
	return c.withDO(c.DO.Session(config))
}

func (c commonTypeDo) Clauses(conds ...clause.Expression) *commonTypeDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c commonTypeDo) Returning(value interface{}, columns ...string) *commonTypeDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c commonTypeDo) Not(conds ...gen.Condition) *commonTypeDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c commonTypeDo) Or(conds ...gen.Condition) *commonTypeDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c commonTypeDo) Select(conds ...field.Expr) *commonTypeDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c commonTypeDo) Where(conds ...gen.Condition) *commonTypeDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c commonTypeDo) Order(conds ...field.Expr) *commonTypeDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c commonTypeDo) Distinct(cols ...field.Expr) *commonTypeDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c commonTypeDo) Omit(cols ...field.Expr) *commonTypeDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c commonTypeDo) Join(table schema.Tabler, on ...field.Expr) *commonTypeDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c commonTypeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *commonTypeDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c commonTypeDo) RightJoin(table schema.Tabler, on ...field.Expr) *commonTypeDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c commonTypeDo) Group(cols ...field.Expr) *commonTypeDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c commonTypeDo) Having(conds ...gen.Condition) *commonTypeDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c commonTypeDo) Limit(limit int) *commonTypeDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c commonTypeDo) Offset(offset int) *commonTypeDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c commonTypeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *commonTypeDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c commonTypeDo) Unscoped() *commonTypeDo {
	return c.withDO(c.DO.Unscoped())
}

func (c commonTypeDo) Create(values ...*model.CommonType) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c commonTypeDo) CreateInBatches(values []*model.CommonType, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c commonTypeDo) Save(values ...*model.CommonType) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c commonTypeDo) First() (*model.CommonType, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonType), nil
	}
}

func (c commonTypeDo) Take() (*model.CommonType, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonType), nil
	}
}

func (c commonTypeDo) Last() (*model.CommonType, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonType), nil
	}
}

func (c commonTypeDo) Find() ([]*model.CommonType, error) {
	result, err := c.DO.Find()
	return result.([]*model.CommonType), err
}

func (c commonTypeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CommonType, err error) {
	buf := make([]*model.CommonType, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c commonTypeDo) FindInBatches(result *[]*model.CommonType, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c commonTypeDo) Attrs(attrs ...field.AssignExpr) *commonTypeDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c commonTypeDo) Assign(attrs ...field.AssignExpr) *commonTypeDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c commonTypeDo) Joins(fields ...field.RelationField) *commonTypeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c commonTypeDo) Preload(fields ...field.RelationField) *commonTypeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c commonTypeDo) FirstOrInit() (*model.CommonType, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonType), nil
	}
}

func (c commonTypeDo) FirstOrCreate() (*model.CommonType, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonType), nil
	}
}

func (c commonTypeDo) FindByPage(offset int, limit int) (result []*model.CommonType, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c commonTypeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c commonTypeDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c commonTypeDo) Delete(models ...*model.CommonType) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *commonTypeDo) withDO(do gen.Dao) *commonTypeDo {
	c.DO = *do.(*gen.DO)
	return c
}
