// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"module.resume/internal/infrastructure/persistence/gorm/model"
)

func newCoverLetter(db *gorm.DB, opts ...gen.DOOption) coverLetter {
	_coverLetter := coverLetter{}

	_coverLetter.coverLetterDo.UseDB(db, opts...)
	_coverLetter.coverLetterDo.UseModel(&model.CoverLetter{})

	tableName := _coverLetter.coverLetterDo.TableName()
	_coverLetter.ALL = field.NewAsterisk(tableName)
	_coverLetter.ID = field.NewInt64(tableName, "id")
	_coverLetter.UsersID = field.NewInt64(tableName, "users_id")
	_coverLetter.Title = field.NewString(tableName, "title")
	_coverLetter.Content = field.NewString(tableName, "content")
	_coverLetter.DeletedAt = field.NewField(tableName, "deleted_at")

	_coverLetter.fillFieldMap()

	return _coverLetter
}

type coverLetter struct {
	coverLetterDo coverLetterDo

	ALL       field.Asterisk
	ID        field.Int64
	UsersID   field.Int64
	Title     field.String
	Content   field.String
	DeletedAt field.Field

	fieldMap map[string]field.Expr
}

func (c coverLetter) Table(newTableName string) *coverLetter {
	c.coverLetterDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c coverLetter) As(alias string) *coverLetter {
	c.coverLetterDo.DO = *(c.coverLetterDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *coverLetter) updateTableName(table string) *coverLetter {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.UsersID = field.NewInt64(table, "users_id")
	c.Title = field.NewString(table, "title")
	c.Content = field.NewString(table, "content")
	c.DeletedAt = field.NewField(table, "deleted_at")

	c.fillFieldMap()

	return c
}

func (c *coverLetter) WithContext(ctx context.Context) *coverLetterDo {
	return c.coverLetterDo.WithContext(ctx)
}

func (c coverLetter) TableName() string { return c.coverLetterDo.TableName() }

func (c coverLetter) Alias() string { return c.coverLetterDo.Alias() }

func (c coverLetter) Columns(cols ...field.Expr) gen.Columns { return c.coverLetterDo.Columns(cols...) }

func (c *coverLetter) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *coverLetter) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 5)
	c.fieldMap["id"] = c.ID
	c.fieldMap["users_id"] = c.UsersID
	c.fieldMap["title"] = c.Title
	c.fieldMap["content"] = c.Content
	c.fieldMap["deleted_at"] = c.DeletedAt
}

func (c coverLetter) clone(db *gorm.DB) coverLetter {
	c.coverLetterDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c coverLetter) replaceDB(db *gorm.DB) coverLetter {
	c.coverLetterDo.ReplaceDB(db)
	return c
}

type coverLetterDo struct{ gen.DO }

func (c coverLetterDo) Debug() *coverLetterDo {
	return c.withDO(c.DO.Debug())
}

func (c coverLetterDo) WithContext(ctx context.Context) *coverLetterDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c coverLetterDo) ReadDB() *coverLetterDo {
	return c.Clauses(dbresolver.Read)
}

func (c coverLetterDo) WriteDB() *coverLetterDo {
	return c.Clauses(dbresolver.Write)
}

func (c coverLetterDo) Session(config *gorm.Session) *coverLetterDo {
	return c.withDO(c.DO.Session(config))
}

func (c coverLetterDo) Clauses(conds ...clause.Expression) *coverLetterDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c coverLetterDo) Returning(value interface{}, columns ...string) *coverLetterDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c coverLetterDo) Not(conds ...gen.Condition) *coverLetterDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c coverLetterDo) Or(conds ...gen.Condition) *coverLetterDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c coverLetterDo) Select(conds ...field.Expr) *coverLetterDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c coverLetterDo) Where(conds ...gen.Condition) *coverLetterDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c coverLetterDo) Order(conds ...field.Expr) *coverLetterDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c coverLetterDo) Distinct(cols ...field.Expr) *coverLetterDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c coverLetterDo) Omit(cols ...field.Expr) *coverLetterDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c coverLetterDo) Join(table schema.Tabler, on ...field.Expr) *coverLetterDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c coverLetterDo) LeftJoin(table schema.Tabler, on ...field.Expr) *coverLetterDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c coverLetterDo) RightJoin(table schema.Tabler, on ...field.Expr) *coverLetterDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c coverLetterDo) Group(cols ...field.Expr) *coverLetterDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c coverLetterDo) Having(conds ...gen.Condition) *coverLetterDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c coverLetterDo) Limit(limit int) *coverLetterDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c coverLetterDo) Offset(offset int) *coverLetterDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c coverLetterDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *coverLetterDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c coverLetterDo) Unscoped() *coverLetterDo {
	return c.withDO(c.DO.Unscoped())
}

func (c coverLetterDo) Create(values ...*model.CoverLetter) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c coverLetterDo) CreateInBatches(values []*model.CoverLetter, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c coverLetterDo) Save(values ...*model.CoverLetter) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c coverLetterDo) First() (*model.CoverLetter, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CoverLetter), nil
	}
}

func (c coverLetterDo) Take() (*model.CoverLetter, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CoverLetter), nil
	}
}

func (c coverLetterDo) Last() (*model.CoverLetter, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CoverLetter), nil
	}
}

func (c coverLetterDo) Find() ([]*model.CoverLetter, error) {
	result, err := c.DO.Find()
	return result.([]*model.CoverLetter), err
}

func (c coverLetterDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CoverLetter, err error) {
	buf := make([]*model.CoverLetter, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c coverLetterDo) FindInBatches(result *[]*model.CoverLetter, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c coverLetterDo) Attrs(attrs ...field.AssignExpr) *coverLetterDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c coverLetterDo) Assign(attrs ...field.AssignExpr) *coverLetterDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c coverLetterDo) Joins(fields ...field.RelationField) *coverLetterDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c coverLetterDo) Preload(fields ...field.RelationField) *coverLetterDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c coverLetterDo) FirstOrInit() (*model.CoverLetter, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CoverLetter), nil
	}
}

func (c coverLetterDo) FirstOrCreate() (*model.CoverLetter, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CoverLetter), nil
	}
}

func (c coverLetterDo) FindByPage(offset int, limit int) (result []*model.CoverLetter, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c coverLetterDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c coverLetterDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c coverLetterDo) Delete(models ...*model.CoverLetter) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *coverLetterDo) withDO(do gen.Dao) *coverLetterDo {
	c.DO = *do.(*gen.DO)
	return c
}
