// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"module.resume/internal/infrastructure/persistence/gorm/model"
)

func newDiary(db *gorm.DB, opts ...gen.DOOption) diary {
	_diary := diary{}

	_diary.diaryDo.UseDB(db, opts...)
	_diary.diaryDo.UseModel(&model.Diary{})

	tableName := _diary.diaryDo.TableName()
	_diary.ALL = field.NewAsterisk(tableName)
	_diary.ID = field.NewInt64(tableName, "id")
	_diary.UsersID = field.NewInt64(tableName, "users_id")
	_diary.WorkExperiencesID = field.NewInt64(tableName, "work_experiences_id")
	_diary.TypesID = field.NewInt64(tableName, "types_id")
	_diary.ProjectsID = field.NewInt64(tableName, "projects_id")
	_diary.Content = field.NewString(tableName, "content")
	_diary.Mood = field.NewString(tableName, "mood")
	_diary.CreatedAt = field.NewTime(tableName, "created_at")
	_diary.UpdatedAt = field.NewTime(tableName, "updated_at")
	_diary.DeletedAt = field.NewField(tableName, "deleted_at")

	_diary.fillFieldMap()

	return _diary
}

type diary struct {
	diaryDo diaryDo

	ALL               field.Asterisk
	ID                field.Int64
	UsersID           field.Int64
	WorkExperiencesID field.Int64
	TypesID           field.Int64
	ProjectsID        field.Int64
	Content           field.String
	Mood              field.String
	CreatedAt         field.Time
	UpdatedAt         field.Time
	DeletedAt         field.Field

	fieldMap map[string]field.Expr
}

func (d diary) Table(newTableName string) *diary {
	d.diaryDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d diary) As(alias string) *diary {
	d.diaryDo.DO = *(d.diaryDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *diary) updateTableName(table string) *diary {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.UsersID = field.NewInt64(table, "users_id")
	d.WorkExperiencesID = field.NewInt64(table, "work_experiences_id")
	d.TypesID = field.NewInt64(table, "types_id")
	d.ProjectsID = field.NewInt64(table, "projects_id")
	d.Content = field.NewString(table, "content")
	d.Mood = field.NewString(table, "mood")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")
	d.DeletedAt = field.NewField(table, "deleted_at")

	d.fillFieldMap()

	return d
}

func (d *diary) WithContext(ctx context.Context) *diaryDo { return d.diaryDo.WithContext(ctx) }

func (d diary) TableName() string { return d.diaryDo.TableName() }

func (d diary) Alias() string { return d.diaryDo.Alias() }

func (d diary) Columns(cols ...field.Expr) gen.Columns { return d.diaryDo.Columns(cols...) }

func (d *diary) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *diary) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 10)
	d.fieldMap["id"] = d.ID
	d.fieldMap["users_id"] = d.UsersID
	d.fieldMap["work_experiences_id"] = d.WorkExperiencesID
	d.fieldMap["types_id"] = d.TypesID
	d.fieldMap["projects_id"] = d.ProjectsID
	d.fieldMap["content"] = d.Content
	d.fieldMap["mood"] = d.Mood
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
	d.fieldMap["deleted_at"] = d.DeletedAt
}

func (d diary) clone(db *gorm.DB) diary {
	d.diaryDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d diary) replaceDB(db *gorm.DB) diary {
	d.diaryDo.ReplaceDB(db)
	return d
}

type diaryDo struct{ gen.DO }

func (d diaryDo) Debug() *diaryDo {
	return d.withDO(d.DO.Debug())
}

func (d diaryDo) WithContext(ctx context.Context) *diaryDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d diaryDo) ReadDB() *diaryDo {
	return d.Clauses(dbresolver.Read)
}

func (d diaryDo) WriteDB() *diaryDo {
	return d.Clauses(dbresolver.Write)
}

func (d diaryDo) Session(config *gorm.Session) *diaryDo {
	return d.withDO(d.DO.Session(config))
}

func (d diaryDo) Clauses(conds ...clause.Expression) *diaryDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d diaryDo) Returning(value interface{}, columns ...string) *diaryDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d diaryDo) Not(conds ...gen.Condition) *diaryDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d diaryDo) Or(conds ...gen.Condition) *diaryDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d diaryDo) Select(conds ...field.Expr) *diaryDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d diaryDo) Where(conds ...gen.Condition) *diaryDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d diaryDo) Order(conds ...field.Expr) *diaryDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d diaryDo) Distinct(cols ...field.Expr) *diaryDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d diaryDo) Omit(cols ...field.Expr) *diaryDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d diaryDo) Join(table schema.Tabler, on ...field.Expr) *diaryDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d diaryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *diaryDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d diaryDo) RightJoin(table schema.Tabler, on ...field.Expr) *diaryDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d diaryDo) Group(cols ...field.Expr) *diaryDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d diaryDo) Having(conds ...gen.Condition) *diaryDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d diaryDo) Limit(limit int) *diaryDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d diaryDo) Offset(offset int) *diaryDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d diaryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *diaryDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d diaryDo) Unscoped() *diaryDo {
	return d.withDO(d.DO.Unscoped())
}

func (d diaryDo) Create(values ...*model.Diary) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d diaryDo) CreateInBatches(values []*model.Diary, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d diaryDo) Save(values ...*model.Diary) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d diaryDo) First() (*model.Diary, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Diary), nil
	}
}

func (d diaryDo) Take() (*model.Diary, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Diary), nil
	}
}

func (d diaryDo) Last() (*model.Diary, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Diary), nil
	}
}

func (d diaryDo) Find() ([]*model.Diary, error) {
	result, err := d.DO.Find()
	return result.([]*model.Diary), err
}

func (d diaryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Diary, err error) {
	buf := make([]*model.Diary, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d diaryDo) FindInBatches(result *[]*model.Diary, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d diaryDo) Attrs(attrs ...field.AssignExpr) *diaryDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d diaryDo) Assign(attrs ...field.AssignExpr) *diaryDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d diaryDo) Joins(fields ...field.RelationField) *diaryDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d diaryDo) Preload(fields ...field.RelationField) *diaryDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d diaryDo) FirstOrInit() (*model.Diary, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Diary), nil
	}
}

func (d diaryDo) FirstOrCreate() (*model.Diary, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Diary), nil
	}
}

func (d diaryDo) FindByPage(offset int, limit int) (result []*model.Diary, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d diaryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d diaryDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d diaryDo) Delete(models ...*model.Diary) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *diaryDo) withDO(do gen.Dao) *diaryDo {
	d.DO = *do.(*gen.DO)
	return d
}
