// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"module.resume/internal/infrastructure/persistence/gorm/model"
)

func newEducation(db *gorm.DB, opts ...gen.DOOption) education {
	_education := education{}

	_education.educationDo.UseDB(db, opts...)
	_education.educationDo.UseModel(&model.Education{})

	tableName := _education.educationDo.TableName()
	_education.ALL = field.NewAsterisk(tableName)
	_education.ID = field.NewInt64(tableName, "id")
	_education.UsersID = field.NewInt64(tableName, "users_id")
	_education.SchoolName = field.NewString(tableName, "school_name")
	_education.Major = field.NewString(tableName, "major")
	_education.Degree = field.NewString(tableName, "degree")
	_education.StartDate = field.NewTime(tableName, "start_date")
	_education.EndDate = field.NewTime(tableName, "end_date")
	_education.Description = field.NewString(tableName, "description")
	_education.DeletedAt = field.NewField(tableName, "deleted_at")

	_education.fillFieldMap()

	return _education
}

type education struct {
	educationDo educationDo

	ALL         field.Asterisk
	ID          field.Int64
	UsersID     field.Int64
	SchoolName  field.String
	Major       field.String
	Degree      field.String
	StartDate   field.Time
	EndDate     field.Time
	Description field.String
	DeletedAt   field.Field

	fieldMap map[string]field.Expr
}

func (e education) Table(newTableName string) *education {
	e.educationDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e education) As(alias string) *education {
	e.educationDo.DO = *(e.educationDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *education) updateTableName(table string) *education {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.UsersID = field.NewInt64(table, "users_id")
	e.SchoolName = field.NewString(table, "school_name")
	e.Major = field.NewString(table, "major")
	e.Degree = field.NewString(table, "degree")
	e.StartDate = field.NewTime(table, "start_date")
	e.EndDate = field.NewTime(table, "end_date")
	e.Description = field.NewString(table, "description")
	e.DeletedAt = field.NewField(table, "deleted_at")

	e.fillFieldMap()

	return e
}

func (e *education) WithContext(ctx context.Context) *educationDo {
	return e.educationDo.WithContext(ctx)
}

func (e education) TableName() string { return e.educationDo.TableName() }

func (e education) Alias() string { return e.educationDo.Alias() }

func (e education) Columns(cols ...field.Expr) gen.Columns { return e.educationDo.Columns(cols...) }

func (e *education) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *education) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 9)
	e.fieldMap["id"] = e.ID
	e.fieldMap["users_id"] = e.UsersID
	e.fieldMap["school_name"] = e.SchoolName
	e.fieldMap["major"] = e.Major
	e.fieldMap["degree"] = e.Degree
	e.fieldMap["start_date"] = e.StartDate
	e.fieldMap["end_date"] = e.EndDate
	e.fieldMap["description"] = e.Description
	e.fieldMap["deleted_at"] = e.DeletedAt
}

func (e education) clone(db *gorm.DB) education {
	e.educationDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e education) replaceDB(db *gorm.DB) education {
	e.educationDo.ReplaceDB(db)
	return e
}

type educationDo struct{ gen.DO }

func (e educationDo) Debug() *educationDo {
	return e.withDO(e.DO.Debug())
}

func (e educationDo) WithContext(ctx context.Context) *educationDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e educationDo) ReadDB() *educationDo {
	return e.Clauses(dbresolver.Read)
}

func (e educationDo) WriteDB() *educationDo {
	return e.Clauses(dbresolver.Write)
}

func (e educationDo) Session(config *gorm.Session) *educationDo {
	return e.withDO(e.DO.Session(config))
}

func (e educationDo) Clauses(conds ...clause.Expression) *educationDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e educationDo) Returning(value interface{}, columns ...string) *educationDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e educationDo) Not(conds ...gen.Condition) *educationDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e educationDo) Or(conds ...gen.Condition) *educationDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e educationDo) Select(conds ...field.Expr) *educationDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e educationDo) Where(conds ...gen.Condition) *educationDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e educationDo) Order(conds ...field.Expr) *educationDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e educationDo) Distinct(cols ...field.Expr) *educationDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e educationDo) Omit(cols ...field.Expr) *educationDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e educationDo) Join(table schema.Tabler, on ...field.Expr) *educationDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e educationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *educationDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e educationDo) RightJoin(table schema.Tabler, on ...field.Expr) *educationDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e educationDo) Group(cols ...field.Expr) *educationDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e educationDo) Having(conds ...gen.Condition) *educationDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e educationDo) Limit(limit int) *educationDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e educationDo) Offset(offset int) *educationDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e educationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *educationDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e educationDo) Unscoped() *educationDo {
	return e.withDO(e.DO.Unscoped())
}

func (e educationDo) Create(values ...*model.Education) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e educationDo) CreateInBatches(values []*model.Education, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e educationDo) Save(values ...*model.Education) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e educationDo) First() (*model.Education, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Education), nil
	}
}

func (e educationDo) Take() (*model.Education, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Education), nil
	}
}

func (e educationDo) Last() (*model.Education, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Education), nil
	}
}

func (e educationDo) Find() ([]*model.Education, error) {
	result, err := e.DO.Find()
	return result.([]*model.Education), err
}

func (e educationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Education, err error) {
	buf := make([]*model.Education, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e educationDo) FindInBatches(result *[]*model.Education, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e educationDo) Attrs(attrs ...field.AssignExpr) *educationDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e educationDo) Assign(attrs ...field.AssignExpr) *educationDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e educationDo) Joins(fields ...field.RelationField) *educationDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e educationDo) Preload(fields ...field.RelationField) *educationDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e educationDo) FirstOrInit() (*model.Education, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Education), nil
	}
}

func (e educationDo) FirstOrCreate() (*model.Education, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Education), nil
	}
}

func (e educationDo) FindByPage(offset int, limit int) (result []*model.Education, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e educationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e educationDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e educationDo) Delete(models ...*model.Education) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *educationDo) withDO(do gen.Dao) *educationDo {
	e.DO = *do.(*gen.DO)
	return e
}
