// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                    db,
		Award:                 newAward(db, opts...),
		Certificate:           newCertificate(db, opts...),
		CommonType:            newCommonType(db, opts...),
		Company:               newCompany(db, opts...),
		CoverLetter:           newCoverLetter(db, opts...),
		Diary:                 newDiary(db, opts...),
		Education:             newEducation(db, opts...),
		Link:                  newLink(db, opts...),
		Project:               newProject(db, opts...),
		Resume:                newResume(db, opts...),
		ResumesAward:          newResumesAward(db, opts...),
		ResumesCertificate:    newResumesCertificate(db, opts...),
		ResumesCoverLetter:    newResumesCoverLetter(db, opts...),
		ResumesEducation:      newResumesEducation(db, opts...),
		ResumesLink:           newResumesLink(db, opts...),
		ResumesProject:        newResumesProject(db, opts...),
		ResumesSkill:          newResumesSkill(db, opts...),
		ResumesWorkExperience: newResumesWorkExperience(db, opts...),
		Skill:                 newSkill(db, opts...),
		User:                  newUser(db, opts...),
		WorkExperience:        newWorkExperience(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Award                 award
	Certificate           certificate
	CommonType            commonType
	Company               company
	CoverLetter           coverLetter
	Diary                 diary
	Education             education
	Link                  link
	Project               project
	Resume                resume
	ResumesAward          resumesAward
	ResumesCertificate    resumesCertificate
	ResumesCoverLetter    resumesCoverLetter
	ResumesEducation      resumesEducation
	ResumesLink           resumesLink
	ResumesProject        resumesProject
	ResumesSkill          resumesSkill
	ResumesWorkExperience resumesWorkExperience
	Skill                 skill
	User                  user
	WorkExperience        workExperience
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		Award:                 q.Award.clone(db),
		Certificate:           q.Certificate.clone(db),
		CommonType:            q.CommonType.clone(db),
		Company:               q.Company.clone(db),
		CoverLetter:           q.CoverLetter.clone(db),
		Diary:                 q.Diary.clone(db),
		Education:             q.Education.clone(db),
		Link:                  q.Link.clone(db),
		Project:               q.Project.clone(db),
		Resume:                q.Resume.clone(db),
		ResumesAward:          q.ResumesAward.clone(db),
		ResumesCertificate:    q.ResumesCertificate.clone(db),
		ResumesCoverLetter:    q.ResumesCoverLetter.clone(db),
		ResumesEducation:      q.ResumesEducation.clone(db),
		ResumesLink:           q.ResumesLink.clone(db),
		ResumesProject:        q.ResumesProject.clone(db),
		ResumesSkill:          q.ResumesSkill.clone(db),
		ResumesWorkExperience: q.ResumesWorkExperience.clone(db),
		Skill:                 q.Skill.clone(db),
		User:                  q.User.clone(db),
		WorkExperience:        q.WorkExperience.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		Award:                 q.Award.replaceDB(db),
		Certificate:           q.Certificate.replaceDB(db),
		CommonType:            q.CommonType.replaceDB(db),
		Company:               q.Company.replaceDB(db),
		CoverLetter:           q.CoverLetter.replaceDB(db),
		Diary:                 q.Diary.replaceDB(db),
		Education:             q.Education.replaceDB(db),
		Link:                  q.Link.replaceDB(db),
		Project:               q.Project.replaceDB(db),
		Resume:                q.Resume.replaceDB(db),
		ResumesAward:          q.ResumesAward.replaceDB(db),
		ResumesCertificate:    q.ResumesCertificate.replaceDB(db),
		ResumesCoverLetter:    q.ResumesCoverLetter.replaceDB(db),
		ResumesEducation:      q.ResumesEducation.replaceDB(db),
		ResumesLink:           q.ResumesLink.replaceDB(db),
		ResumesProject:        q.ResumesProject.replaceDB(db),
		ResumesSkill:          q.ResumesSkill.replaceDB(db),
		ResumesWorkExperience: q.ResumesWorkExperience.replaceDB(db),
		Skill:                 q.Skill.replaceDB(db),
		User:                  q.User.replaceDB(db),
		WorkExperience:        q.WorkExperience.replaceDB(db),
	}
}

type queryCtx struct {
	Award                 *awardDo
	Certificate           *certificateDo
	CommonType            *commonTypeDo
	Company               *companyDo
	CoverLetter           *coverLetterDo
	Diary                 *diaryDo
	Education             *educationDo
	Link                  *linkDo
	Project               *projectDo
	Resume                *resumeDo
	ResumesAward          *resumesAwardDo
	ResumesCertificate    *resumesCertificateDo
	ResumesCoverLetter    *resumesCoverLetterDo
	ResumesEducation      *resumesEducationDo
	ResumesLink           *resumesLinkDo
	ResumesProject        *resumesProjectDo
	ResumesSkill          *resumesSkillDo
	ResumesWorkExperience *resumesWorkExperienceDo
	Skill                 *skillDo
	User                  *userDo
	WorkExperience        *workExperienceDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Award:                 q.Award.WithContext(ctx),
		Certificate:           q.Certificate.WithContext(ctx),
		CommonType:            q.CommonType.WithContext(ctx),
		Company:               q.Company.WithContext(ctx),
		CoverLetter:           q.CoverLetter.WithContext(ctx),
		Diary:                 q.Diary.WithContext(ctx),
		Education:             q.Education.WithContext(ctx),
		Link:                  q.Link.WithContext(ctx),
		Project:               q.Project.WithContext(ctx),
		Resume:                q.Resume.WithContext(ctx),
		ResumesAward:          q.ResumesAward.WithContext(ctx),
		ResumesCertificate:    q.ResumesCertificate.WithContext(ctx),
		ResumesCoverLetter:    q.ResumesCoverLetter.WithContext(ctx),
		ResumesEducation:      q.ResumesEducation.WithContext(ctx),
		ResumesLink:           q.ResumesLink.WithContext(ctx),
		ResumesProject:        q.ResumesProject.WithContext(ctx),
		ResumesSkill:          q.ResumesSkill.WithContext(ctx),
		ResumesWorkExperience: q.ResumesWorkExperience.WithContext(ctx),
		Skill:                 q.Skill.WithContext(ctx),
		User:                  q.User.WithContext(ctx),
		WorkExperience:        q.WorkExperience.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
