// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"module.resume/internal/infrastructure/persistence/gorm/model"
)

func newResumesLink(db *gorm.DB, opts ...gen.DOOption) resumesLink {
	_resumesLink := resumesLink{}

	_resumesLink.resumesLinkDo.UseDB(db, opts...)
	_resumesLink.resumesLinkDo.UseModel(&model.ResumesLink{})

	tableName := _resumesLink.resumesLinkDo.TableName()
	_resumesLink.ALL = field.NewAsterisk(tableName)
	_resumesLink.ResumesID = field.NewInt64(tableName, "resumes_id")
	_resumesLink.LinksID = field.NewInt64(tableName, "links_id")

	_resumesLink.fillFieldMap()

	return _resumesLink
}

type resumesLink struct {
	resumesLinkDo resumesLinkDo

	ALL       field.Asterisk
	ResumesID field.Int64
	LinksID   field.Int64

	fieldMap map[string]field.Expr
}

func (r resumesLink) Table(newTableName string) *resumesLink {
	r.resumesLinkDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resumesLink) As(alias string) *resumesLink {
	r.resumesLinkDo.DO = *(r.resumesLinkDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resumesLink) updateTableName(table string) *resumesLink {
	r.ALL = field.NewAsterisk(table)
	r.ResumesID = field.NewInt64(table, "resumes_id")
	r.LinksID = field.NewInt64(table, "links_id")

	r.fillFieldMap()

	return r
}

func (r *resumesLink) WithContext(ctx context.Context) *resumesLinkDo {
	return r.resumesLinkDo.WithContext(ctx)
}

func (r resumesLink) TableName() string { return r.resumesLinkDo.TableName() }

func (r resumesLink) Alias() string { return r.resumesLinkDo.Alias() }

func (r resumesLink) Columns(cols ...field.Expr) gen.Columns { return r.resumesLinkDo.Columns(cols...) }

func (r *resumesLink) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resumesLink) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 2)
	r.fieldMap["resumes_id"] = r.ResumesID
	r.fieldMap["links_id"] = r.LinksID
}

func (r resumesLink) clone(db *gorm.DB) resumesLink {
	r.resumesLinkDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resumesLink) replaceDB(db *gorm.DB) resumesLink {
	r.resumesLinkDo.ReplaceDB(db)
	return r
}

type resumesLinkDo struct{ gen.DO }

func (r resumesLinkDo) Debug() *resumesLinkDo {
	return r.withDO(r.DO.Debug())
}

func (r resumesLinkDo) WithContext(ctx context.Context) *resumesLinkDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resumesLinkDo) ReadDB() *resumesLinkDo {
	return r.Clauses(dbresolver.Read)
}

func (r resumesLinkDo) WriteDB() *resumesLinkDo {
	return r.Clauses(dbresolver.Write)
}

func (r resumesLinkDo) Session(config *gorm.Session) *resumesLinkDo {
	return r.withDO(r.DO.Session(config))
}

func (r resumesLinkDo) Clauses(conds ...clause.Expression) *resumesLinkDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resumesLinkDo) Returning(value interface{}, columns ...string) *resumesLinkDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resumesLinkDo) Not(conds ...gen.Condition) *resumesLinkDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resumesLinkDo) Or(conds ...gen.Condition) *resumesLinkDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resumesLinkDo) Select(conds ...field.Expr) *resumesLinkDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resumesLinkDo) Where(conds ...gen.Condition) *resumesLinkDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resumesLinkDo) Order(conds ...field.Expr) *resumesLinkDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resumesLinkDo) Distinct(cols ...field.Expr) *resumesLinkDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resumesLinkDo) Omit(cols ...field.Expr) *resumesLinkDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resumesLinkDo) Join(table schema.Tabler, on ...field.Expr) *resumesLinkDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resumesLinkDo) LeftJoin(table schema.Tabler, on ...field.Expr) *resumesLinkDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resumesLinkDo) RightJoin(table schema.Tabler, on ...field.Expr) *resumesLinkDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resumesLinkDo) Group(cols ...field.Expr) *resumesLinkDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resumesLinkDo) Having(conds ...gen.Condition) *resumesLinkDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resumesLinkDo) Limit(limit int) *resumesLinkDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resumesLinkDo) Offset(offset int) *resumesLinkDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resumesLinkDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *resumesLinkDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resumesLinkDo) Unscoped() *resumesLinkDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resumesLinkDo) Create(values ...*model.ResumesLink) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resumesLinkDo) CreateInBatches(values []*model.ResumesLink, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resumesLinkDo) Save(values ...*model.ResumesLink) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resumesLinkDo) First() (*model.ResumesLink, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesLink), nil
	}
}

func (r resumesLinkDo) Take() (*model.ResumesLink, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesLink), nil
	}
}

func (r resumesLinkDo) Last() (*model.ResumesLink, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesLink), nil
	}
}

func (r resumesLinkDo) Find() ([]*model.ResumesLink, error) {
	result, err := r.DO.Find()
	return result.([]*model.ResumesLink), err
}

func (r resumesLinkDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResumesLink, err error) {
	buf := make([]*model.ResumesLink, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resumesLinkDo) FindInBatches(result *[]*model.ResumesLink, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resumesLinkDo) Attrs(attrs ...field.AssignExpr) *resumesLinkDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resumesLinkDo) Assign(attrs ...field.AssignExpr) *resumesLinkDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resumesLinkDo) Joins(fields ...field.RelationField) *resumesLinkDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resumesLinkDo) Preload(fields ...field.RelationField) *resumesLinkDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resumesLinkDo) FirstOrInit() (*model.ResumesLink, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesLink), nil
	}
}

func (r resumesLinkDo) FirstOrCreate() (*model.ResumesLink, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesLink), nil
	}
}

func (r resumesLinkDo) FindByPage(offset int, limit int) (result []*model.ResumesLink, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resumesLinkDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resumesLinkDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resumesLinkDo) Delete(models ...*model.ResumesLink) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resumesLinkDo) withDO(do gen.Dao) *resumesLinkDo {
	r.DO = *do.(*gen.DO)
	return r
}
