// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"module.resume/internal/infrastructure/persistence/gorm/model"
)

func newResumesSkill(db *gorm.DB, opts ...gen.DOOption) resumesSkill {
	_resumesSkill := resumesSkill{}

	_resumesSkill.resumesSkillDo.UseDB(db, opts...)
	_resumesSkill.resumesSkillDo.UseModel(&model.ResumesSkill{})

	tableName := _resumesSkill.resumesSkillDo.TableName()
	_resumesSkill.ALL = field.NewAsterisk(tableName)
	_resumesSkill.ResumesID = field.NewInt64(tableName, "resumes_id")
	_resumesSkill.SkillsID = field.NewInt64(tableName, "skills_id")
	_resumesSkill.Order = field.NewInt32(tableName, "order")
	_resumesSkill.PrivateMemo = field.NewString(tableName, "private_memo")

	_resumesSkill.fillFieldMap()

	return _resumesSkill
}

type resumesSkill struct {
	resumesSkillDo resumesSkillDo

	ALL         field.Asterisk
	ResumesID   field.Int64
	SkillsID    field.Int64
	Order       field.Int32
	PrivateMemo field.String

	fieldMap map[string]field.Expr
}

func (r resumesSkill) Table(newTableName string) *resumesSkill {
	r.resumesSkillDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resumesSkill) As(alias string) *resumesSkill {
	r.resumesSkillDo.DO = *(r.resumesSkillDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resumesSkill) updateTableName(table string) *resumesSkill {
	r.ALL = field.NewAsterisk(table)
	r.ResumesID = field.NewInt64(table, "resumes_id")
	r.SkillsID = field.NewInt64(table, "skills_id")
	r.Order = field.NewInt32(table, "order")
	r.PrivateMemo = field.NewString(table, "private_memo")

	r.fillFieldMap()

	return r
}

func (r *resumesSkill) WithContext(ctx context.Context) *resumesSkillDo {
	return r.resumesSkillDo.WithContext(ctx)
}

func (r resumesSkill) TableName() string { return r.resumesSkillDo.TableName() }

func (r resumesSkill) Alias() string { return r.resumesSkillDo.Alias() }

func (r resumesSkill) Columns(cols ...field.Expr) gen.Columns {
	return r.resumesSkillDo.Columns(cols...)
}

func (r *resumesSkill) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resumesSkill) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 4)
	r.fieldMap["resumes_id"] = r.ResumesID
	r.fieldMap["skills_id"] = r.SkillsID
	r.fieldMap["order"] = r.Order
	r.fieldMap["private_memo"] = r.PrivateMemo
}

func (r resumesSkill) clone(db *gorm.DB) resumesSkill {
	r.resumesSkillDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resumesSkill) replaceDB(db *gorm.DB) resumesSkill {
	r.resumesSkillDo.ReplaceDB(db)
	return r
}

type resumesSkillDo struct{ gen.DO }

func (r resumesSkillDo) Debug() *resumesSkillDo {
	return r.withDO(r.DO.Debug())
}

func (r resumesSkillDo) WithContext(ctx context.Context) *resumesSkillDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resumesSkillDo) ReadDB() *resumesSkillDo {
	return r.Clauses(dbresolver.Read)
}

func (r resumesSkillDo) WriteDB() *resumesSkillDo {
	return r.Clauses(dbresolver.Write)
}

func (r resumesSkillDo) Session(config *gorm.Session) *resumesSkillDo {
	return r.withDO(r.DO.Session(config))
}

func (r resumesSkillDo) Clauses(conds ...clause.Expression) *resumesSkillDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resumesSkillDo) Returning(value interface{}, columns ...string) *resumesSkillDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resumesSkillDo) Not(conds ...gen.Condition) *resumesSkillDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resumesSkillDo) Or(conds ...gen.Condition) *resumesSkillDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resumesSkillDo) Select(conds ...field.Expr) *resumesSkillDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resumesSkillDo) Where(conds ...gen.Condition) *resumesSkillDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resumesSkillDo) Order(conds ...field.Expr) *resumesSkillDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resumesSkillDo) Distinct(cols ...field.Expr) *resumesSkillDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resumesSkillDo) Omit(cols ...field.Expr) *resumesSkillDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resumesSkillDo) Join(table schema.Tabler, on ...field.Expr) *resumesSkillDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resumesSkillDo) LeftJoin(table schema.Tabler, on ...field.Expr) *resumesSkillDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resumesSkillDo) RightJoin(table schema.Tabler, on ...field.Expr) *resumesSkillDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resumesSkillDo) Group(cols ...field.Expr) *resumesSkillDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resumesSkillDo) Having(conds ...gen.Condition) *resumesSkillDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resumesSkillDo) Limit(limit int) *resumesSkillDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resumesSkillDo) Offset(offset int) *resumesSkillDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resumesSkillDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *resumesSkillDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resumesSkillDo) Unscoped() *resumesSkillDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resumesSkillDo) Create(values ...*model.ResumesSkill) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resumesSkillDo) CreateInBatches(values []*model.ResumesSkill, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resumesSkillDo) Save(values ...*model.ResumesSkill) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resumesSkillDo) First() (*model.ResumesSkill, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesSkill), nil
	}
}

func (r resumesSkillDo) Take() (*model.ResumesSkill, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesSkill), nil
	}
}

func (r resumesSkillDo) Last() (*model.ResumesSkill, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesSkill), nil
	}
}

func (r resumesSkillDo) Find() ([]*model.ResumesSkill, error) {
	result, err := r.DO.Find()
	return result.([]*model.ResumesSkill), err
}

func (r resumesSkillDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResumesSkill, err error) {
	buf := make([]*model.ResumesSkill, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resumesSkillDo) FindInBatches(result *[]*model.ResumesSkill, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resumesSkillDo) Attrs(attrs ...field.AssignExpr) *resumesSkillDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resumesSkillDo) Assign(attrs ...field.AssignExpr) *resumesSkillDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resumesSkillDo) Joins(fields ...field.RelationField) *resumesSkillDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resumesSkillDo) Preload(fields ...field.RelationField) *resumesSkillDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resumesSkillDo) FirstOrInit() (*model.ResumesSkill, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesSkill), nil
	}
}

func (r resumesSkillDo) FirstOrCreate() (*model.ResumesSkill, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesSkill), nil
	}
}

func (r resumesSkillDo) FindByPage(offset int, limit int) (result []*model.ResumesSkill, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resumesSkillDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resumesSkillDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resumesSkillDo) Delete(models ...*model.ResumesSkill) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resumesSkillDo) withDO(do gen.Dao) *resumesSkillDo {
	r.DO = *do.(*gen.DO)
	return r
}
