// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"module.resume/internal/infrastructure/persistence/gorm/model"
)

func newResumesCertificate(db *gorm.DB, opts ...gen.DOOption) resumesCertificate {
	_resumesCertificate := resumesCertificate{}

	_resumesCertificate.resumesCertificateDo.UseDB(db, opts...)
	_resumesCertificate.resumesCertificateDo.UseModel(&model.ResumesCertificate{})

	tableName := _resumesCertificate.resumesCertificateDo.TableName()
	_resumesCertificate.ALL = field.NewAsterisk(tableName)
	_resumesCertificate.ResumesID = field.NewInt64(tableName, "resumes_id")
	_resumesCertificate.CertificatesID = field.NewInt64(tableName, "certificates_id")
	_resumesCertificate.Order = field.NewInt32(tableName, "order")
	_resumesCertificate.PrivateMemo = field.NewString(tableName, "private_memo")

	_resumesCertificate.fillFieldMap()

	return _resumesCertificate
}

type resumesCertificate struct {
	resumesCertificateDo resumesCertificateDo

	ALL            field.Asterisk
	ResumesID      field.Int64
	CertificatesID field.Int64
	Order          field.Int32
	PrivateMemo    field.String

	fieldMap map[string]field.Expr
}

func (r resumesCertificate) Table(newTableName string) *resumesCertificate {
	r.resumesCertificateDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resumesCertificate) As(alias string) *resumesCertificate {
	r.resumesCertificateDo.DO = *(r.resumesCertificateDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resumesCertificate) updateTableName(table string) *resumesCertificate {
	r.ALL = field.NewAsterisk(table)
	r.ResumesID = field.NewInt64(table, "resumes_id")
	r.CertificatesID = field.NewInt64(table, "certificates_id")
	r.Order = field.NewInt32(table, "order")
	r.PrivateMemo = field.NewString(table, "private_memo")

	r.fillFieldMap()

	return r
}

func (r *resumesCertificate) WithContext(ctx context.Context) *resumesCertificateDo {
	return r.resumesCertificateDo.WithContext(ctx)
}

func (r resumesCertificate) TableName() string { return r.resumesCertificateDo.TableName() }

func (r resumesCertificate) Alias() string { return r.resumesCertificateDo.Alias() }

func (r resumesCertificate) Columns(cols ...field.Expr) gen.Columns {
	return r.resumesCertificateDo.Columns(cols...)
}

func (r *resumesCertificate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resumesCertificate) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 4)
	r.fieldMap["resumes_id"] = r.ResumesID
	r.fieldMap["certificates_id"] = r.CertificatesID
	r.fieldMap["order"] = r.Order
	r.fieldMap["private_memo"] = r.PrivateMemo
}

func (r resumesCertificate) clone(db *gorm.DB) resumesCertificate {
	r.resumesCertificateDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resumesCertificate) replaceDB(db *gorm.DB) resumesCertificate {
	r.resumesCertificateDo.ReplaceDB(db)
	return r
}

type resumesCertificateDo struct{ gen.DO }

func (r resumesCertificateDo) Debug() *resumesCertificateDo {
	return r.withDO(r.DO.Debug())
}

func (r resumesCertificateDo) WithContext(ctx context.Context) *resumesCertificateDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resumesCertificateDo) ReadDB() *resumesCertificateDo {
	return r.Clauses(dbresolver.Read)
}

func (r resumesCertificateDo) WriteDB() *resumesCertificateDo {
	return r.Clauses(dbresolver.Write)
}

func (r resumesCertificateDo) Session(config *gorm.Session) *resumesCertificateDo {
	return r.withDO(r.DO.Session(config))
}

func (r resumesCertificateDo) Clauses(conds ...clause.Expression) *resumesCertificateDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resumesCertificateDo) Returning(value interface{}, columns ...string) *resumesCertificateDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resumesCertificateDo) Not(conds ...gen.Condition) *resumesCertificateDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resumesCertificateDo) Or(conds ...gen.Condition) *resumesCertificateDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resumesCertificateDo) Select(conds ...field.Expr) *resumesCertificateDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resumesCertificateDo) Where(conds ...gen.Condition) *resumesCertificateDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resumesCertificateDo) Order(conds ...field.Expr) *resumesCertificateDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resumesCertificateDo) Distinct(cols ...field.Expr) *resumesCertificateDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resumesCertificateDo) Omit(cols ...field.Expr) *resumesCertificateDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resumesCertificateDo) Join(table schema.Tabler, on ...field.Expr) *resumesCertificateDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resumesCertificateDo) LeftJoin(table schema.Tabler, on ...field.Expr) *resumesCertificateDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resumesCertificateDo) RightJoin(table schema.Tabler, on ...field.Expr) *resumesCertificateDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resumesCertificateDo) Group(cols ...field.Expr) *resumesCertificateDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resumesCertificateDo) Having(conds ...gen.Condition) *resumesCertificateDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resumesCertificateDo) Limit(limit int) *resumesCertificateDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resumesCertificateDo) Offset(offset int) *resumesCertificateDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resumesCertificateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *resumesCertificateDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resumesCertificateDo) Unscoped() *resumesCertificateDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resumesCertificateDo) Create(values ...*model.ResumesCertificate) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resumesCertificateDo) CreateInBatches(values []*model.ResumesCertificate, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resumesCertificateDo) Save(values ...*model.ResumesCertificate) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resumesCertificateDo) First() (*model.ResumesCertificate, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesCertificate), nil
	}
}

func (r resumesCertificateDo) Take() (*model.ResumesCertificate, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesCertificate), nil
	}
}

func (r resumesCertificateDo) Last() (*model.ResumesCertificate, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesCertificate), nil
	}
}

func (r resumesCertificateDo) Find() ([]*model.ResumesCertificate, error) {
	result, err := r.DO.Find()
	return result.([]*model.ResumesCertificate), err
}

func (r resumesCertificateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResumesCertificate, err error) {
	buf := make([]*model.ResumesCertificate, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resumesCertificateDo) FindInBatches(result *[]*model.ResumesCertificate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resumesCertificateDo) Attrs(attrs ...field.AssignExpr) *resumesCertificateDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resumesCertificateDo) Assign(attrs ...field.AssignExpr) *resumesCertificateDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resumesCertificateDo) Joins(fields ...field.RelationField) *resumesCertificateDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resumesCertificateDo) Preload(fields ...field.RelationField) *resumesCertificateDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resumesCertificateDo) FirstOrInit() (*model.ResumesCertificate, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesCertificate), nil
	}
}

func (r resumesCertificateDo) FirstOrCreate() (*model.ResumesCertificate, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesCertificate), nil
	}
}

func (r resumesCertificateDo) FindByPage(offset int, limit int) (result []*model.ResumesCertificate, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resumesCertificateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resumesCertificateDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resumesCertificateDo) Delete(models ...*model.ResumesCertificate) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resumesCertificateDo) withDO(do gen.Dao) *resumesCertificateDo {
	r.DO = *do.(*gen.DO)
	return r
}
