// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"module.resume/internal/infrastructure/persistence/gorm/model"
)

func newResumesWorkExperience(db *gorm.DB, opts ...gen.DOOption) resumesWorkExperience {
	_resumesWorkExperience := resumesWorkExperience{}

	_resumesWorkExperience.resumesWorkExperienceDo.UseDB(db, opts...)
	_resumesWorkExperience.resumesWorkExperienceDo.UseModel(&model.ResumesWorkExperience{})

	tableName := _resumesWorkExperience.resumesWorkExperienceDo.TableName()
	_resumesWorkExperience.ALL = field.NewAsterisk(tableName)
	_resumesWorkExperience.ResumesID = field.NewInt64(tableName, "resumes_id")
	_resumesWorkExperience.WorkExperiencesID = field.NewInt64(tableName, "work_experiences_id")
	_resumesWorkExperience.Order = field.NewInt32(tableName, "order")
	_resumesWorkExperience.PrivateNote = field.NewString(tableName, "private_note")

	_resumesWorkExperience.fillFieldMap()

	return _resumesWorkExperience
}

type resumesWorkExperience struct {
	resumesWorkExperienceDo resumesWorkExperienceDo

	ALL               field.Asterisk
	ResumesID         field.Int64
	WorkExperiencesID field.Int64
	Order             field.Int32
	PrivateNote       field.String

	fieldMap map[string]field.Expr
}

func (r resumesWorkExperience) Table(newTableName string) *resumesWorkExperience {
	r.resumesWorkExperienceDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resumesWorkExperience) As(alias string) *resumesWorkExperience {
	r.resumesWorkExperienceDo.DO = *(r.resumesWorkExperienceDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resumesWorkExperience) updateTableName(table string) *resumesWorkExperience {
	r.ALL = field.NewAsterisk(table)
	r.ResumesID = field.NewInt64(table, "resumes_id")
	r.WorkExperiencesID = field.NewInt64(table, "work_experiences_id")
	r.Order = field.NewInt32(table, "order")
	r.PrivateNote = field.NewString(table, "private_note")

	r.fillFieldMap()

	return r
}

func (r *resumesWorkExperience) WithContext(ctx context.Context) *resumesWorkExperienceDo {
	return r.resumesWorkExperienceDo.WithContext(ctx)
}

func (r resumesWorkExperience) TableName() string { return r.resumesWorkExperienceDo.TableName() }

func (r resumesWorkExperience) Alias() string { return r.resumesWorkExperienceDo.Alias() }

func (r resumesWorkExperience) Columns(cols ...field.Expr) gen.Columns {
	return r.resumesWorkExperienceDo.Columns(cols...)
}

func (r *resumesWorkExperience) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resumesWorkExperience) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 4)
	r.fieldMap["resumes_id"] = r.ResumesID
	r.fieldMap["work_experiences_id"] = r.WorkExperiencesID
	r.fieldMap["order"] = r.Order
	r.fieldMap["private_note"] = r.PrivateNote
}

func (r resumesWorkExperience) clone(db *gorm.DB) resumesWorkExperience {
	r.resumesWorkExperienceDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resumesWorkExperience) replaceDB(db *gorm.DB) resumesWorkExperience {
	r.resumesWorkExperienceDo.ReplaceDB(db)
	return r
}

type resumesWorkExperienceDo struct{ gen.DO }

func (r resumesWorkExperienceDo) Debug() *resumesWorkExperienceDo {
	return r.withDO(r.DO.Debug())
}

func (r resumesWorkExperienceDo) WithContext(ctx context.Context) *resumesWorkExperienceDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resumesWorkExperienceDo) ReadDB() *resumesWorkExperienceDo {
	return r.Clauses(dbresolver.Read)
}

func (r resumesWorkExperienceDo) WriteDB() *resumesWorkExperienceDo {
	return r.Clauses(dbresolver.Write)
}

func (r resumesWorkExperienceDo) Session(config *gorm.Session) *resumesWorkExperienceDo {
	return r.withDO(r.DO.Session(config))
}

func (r resumesWorkExperienceDo) Clauses(conds ...clause.Expression) *resumesWorkExperienceDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resumesWorkExperienceDo) Returning(value interface{}, columns ...string) *resumesWorkExperienceDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resumesWorkExperienceDo) Not(conds ...gen.Condition) *resumesWorkExperienceDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resumesWorkExperienceDo) Or(conds ...gen.Condition) *resumesWorkExperienceDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resumesWorkExperienceDo) Select(conds ...field.Expr) *resumesWorkExperienceDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resumesWorkExperienceDo) Where(conds ...gen.Condition) *resumesWorkExperienceDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resumesWorkExperienceDo) Order(conds ...field.Expr) *resumesWorkExperienceDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resumesWorkExperienceDo) Distinct(cols ...field.Expr) *resumesWorkExperienceDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resumesWorkExperienceDo) Omit(cols ...field.Expr) *resumesWorkExperienceDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resumesWorkExperienceDo) Join(table schema.Tabler, on ...field.Expr) *resumesWorkExperienceDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resumesWorkExperienceDo) LeftJoin(table schema.Tabler, on ...field.Expr) *resumesWorkExperienceDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resumesWorkExperienceDo) RightJoin(table schema.Tabler, on ...field.Expr) *resumesWorkExperienceDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resumesWorkExperienceDo) Group(cols ...field.Expr) *resumesWorkExperienceDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resumesWorkExperienceDo) Having(conds ...gen.Condition) *resumesWorkExperienceDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resumesWorkExperienceDo) Limit(limit int) *resumesWorkExperienceDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resumesWorkExperienceDo) Offset(offset int) *resumesWorkExperienceDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resumesWorkExperienceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *resumesWorkExperienceDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resumesWorkExperienceDo) Unscoped() *resumesWorkExperienceDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resumesWorkExperienceDo) Create(values ...*model.ResumesWorkExperience) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resumesWorkExperienceDo) CreateInBatches(values []*model.ResumesWorkExperience, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resumesWorkExperienceDo) Save(values ...*model.ResumesWorkExperience) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resumesWorkExperienceDo) First() (*model.ResumesWorkExperience, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesWorkExperience), nil
	}
}

func (r resumesWorkExperienceDo) Take() (*model.ResumesWorkExperience, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesWorkExperience), nil
	}
}

func (r resumesWorkExperienceDo) Last() (*model.ResumesWorkExperience, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesWorkExperience), nil
	}
}

func (r resumesWorkExperienceDo) Find() ([]*model.ResumesWorkExperience, error) {
	result, err := r.DO.Find()
	return result.([]*model.ResumesWorkExperience), err
}

func (r resumesWorkExperienceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResumesWorkExperience, err error) {
	buf := make([]*model.ResumesWorkExperience, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resumesWorkExperienceDo) FindInBatches(result *[]*model.ResumesWorkExperience, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resumesWorkExperienceDo) Attrs(attrs ...field.AssignExpr) *resumesWorkExperienceDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resumesWorkExperienceDo) Assign(attrs ...field.AssignExpr) *resumesWorkExperienceDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resumesWorkExperienceDo) Joins(fields ...field.RelationField) *resumesWorkExperienceDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resumesWorkExperienceDo) Preload(fields ...field.RelationField) *resumesWorkExperienceDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resumesWorkExperienceDo) FirstOrInit() (*model.ResumesWorkExperience, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesWorkExperience), nil
	}
}

func (r resumesWorkExperienceDo) FirstOrCreate() (*model.ResumesWorkExperience, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesWorkExperience), nil
	}
}

func (r resumesWorkExperienceDo) FindByPage(offset int, limit int) (result []*model.ResumesWorkExperience, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resumesWorkExperienceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resumesWorkExperienceDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resumesWorkExperienceDo) Delete(models ...*model.ResumesWorkExperience) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resumesWorkExperienceDo) withDO(do gen.Dao) *resumesWorkExperienceDo {
	r.DO = *do.(*gen.DO)
	return r
}
