// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"module.resume/internal/infrastructure/persistence/gorm/model"
)

func newResumesProject(db *gorm.DB, opts ...gen.DOOption) resumesProject {
	_resumesProject := resumesProject{}

	_resumesProject.resumesProjectDo.UseDB(db, opts...)
	_resumesProject.resumesProjectDo.UseModel(&model.ResumesProject{})

	tableName := _resumesProject.resumesProjectDo.TableName()
	_resumesProject.ALL = field.NewAsterisk(tableName)
	_resumesProject.ResumesID = field.NewInt64(tableName, "resumes_id")
	_resumesProject.ProjectsID = field.NewInt64(tableName, "projects_id")
	_resumesProject.Order = field.NewInt32(tableName, "order")
	_resumesProject.PrivateNote = field.NewString(tableName, "private_note")

	_resumesProject.fillFieldMap()

	return _resumesProject
}

type resumesProject struct {
	resumesProjectDo resumesProjectDo

	ALL         field.Asterisk
	ResumesID   field.Int64
	ProjectsID  field.Int64
	Order       field.Int32
	PrivateNote field.String

	fieldMap map[string]field.Expr
}

func (r resumesProject) Table(newTableName string) *resumesProject {
	r.resumesProjectDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resumesProject) As(alias string) *resumesProject {
	r.resumesProjectDo.DO = *(r.resumesProjectDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resumesProject) updateTableName(table string) *resumesProject {
	r.ALL = field.NewAsterisk(table)
	r.ResumesID = field.NewInt64(table, "resumes_id")
	r.ProjectsID = field.NewInt64(table, "projects_id")
	r.Order = field.NewInt32(table, "order")
	r.PrivateNote = field.NewString(table, "private_note")

	r.fillFieldMap()

	return r
}

func (r *resumesProject) WithContext(ctx context.Context) *resumesProjectDo {
	return r.resumesProjectDo.WithContext(ctx)
}

func (r resumesProject) TableName() string { return r.resumesProjectDo.TableName() }

func (r resumesProject) Alias() string { return r.resumesProjectDo.Alias() }

func (r resumesProject) Columns(cols ...field.Expr) gen.Columns {
	return r.resumesProjectDo.Columns(cols...)
}

func (r *resumesProject) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resumesProject) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 4)
	r.fieldMap["resumes_id"] = r.ResumesID
	r.fieldMap["projects_id"] = r.ProjectsID
	r.fieldMap["order"] = r.Order
	r.fieldMap["private_note"] = r.PrivateNote
}

func (r resumesProject) clone(db *gorm.DB) resumesProject {
	r.resumesProjectDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resumesProject) replaceDB(db *gorm.DB) resumesProject {
	r.resumesProjectDo.ReplaceDB(db)
	return r
}

type resumesProjectDo struct{ gen.DO }

func (r resumesProjectDo) Debug() *resumesProjectDo {
	return r.withDO(r.DO.Debug())
}

func (r resumesProjectDo) WithContext(ctx context.Context) *resumesProjectDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resumesProjectDo) ReadDB() *resumesProjectDo {
	return r.Clauses(dbresolver.Read)
}

func (r resumesProjectDo) WriteDB() *resumesProjectDo {
	return r.Clauses(dbresolver.Write)
}

func (r resumesProjectDo) Session(config *gorm.Session) *resumesProjectDo {
	return r.withDO(r.DO.Session(config))
}

func (r resumesProjectDo) Clauses(conds ...clause.Expression) *resumesProjectDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resumesProjectDo) Returning(value interface{}, columns ...string) *resumesProjectDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resumesProjectDo) Not(conds ...gen.Condition) *resumesProjectDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resumesProjectDo) Or(conds ...gen.Condition) *resumesProjectDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resumesProjectDo) Select(conds ...field.Expr) *resumesProjectDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resumesProjectDo) Where(conds ...gen.Condition) *resumesProjectDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resumesProjectDo) Order(conds ...field.Expr) *resumesProjectDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resumesProjectDo) Distinct(cols ...field.Expr) *resumesProjectDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resumesProjectDo) Omit(cols ...field.Expr) *resumesProjectDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resumesProjectDo) Join(table schema.Tabler, on ...field.Expr) *resumesProjectDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resumesProjectDo) LeftJoin(table schema.Tabler, on ...field.Expr) *resumesProjectDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resumesProjectDo) RightJoin(table schema.Tabler, on ...field.Expr) *resumesProjectDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resumesProjectDo) Group(cols ...field.Expr) *resumesProjectDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resumesProjectDo) Having(conds ...gen.Condition) *resumesProjectDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resumesProjectDo) Limit(limit int) *resumesProjectDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resumesProjectDo) Offset(offset int) *resumesProjectDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resumesProjectDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *resumesProjectDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resumesProjectDo) Unscoped() *resumesProjectDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resumesProjectDo) Create(values ...*model.ResumesProject) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resumesProjectDo) CreateInBatches(values []*model.ResumesProject, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resumesProjectDo) Save(values ...*model.ResumesProject) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resumesProjectDo) First() (*model.ResumesProject, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesProject), nil
	}
}

func (r resumesProjectDo) Take() (*model.ResumesProject, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesProject), nil
	}
}

func (r resumesProjectDo) Last() (*model.ResumesProject, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesProject), nil
	}
}

func (r resumesProjectDo) Find() ([]*model.ResumesProject, error) {
	result, err := r.DO.Find()
	return result.([]*model.ResumesProject), err
}

func (r resumesProjectDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResumesProject, err error) {
	buf := make([]*model.ResumesProject, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resumesProjectDo) FindInBatches(result *[]*model.ResumesProject, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resumesProjectDo) Attrs(attrs ...field.AssignExpr) *resumesProjectDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resumesProjectDo) Assign(attrs ...field.AssignExpr) *resumesProjectDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resumesProjectDo) Joins(fields ...field.RelationField) *resumesProjectDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resumesProjectDo) Preload(fields ...field.RelationField) *resumesProjectDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resumesProjectDo) FirstOrInit() (*model.ResumesProject, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesProject), nil
	}
}

func (r resumesProjectDo) FirstOrCreate() (*model.ResumesProject, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesProject), nil
	}
}

func (r resumesProjectDo) FindByPage(offset int, limit int) (result []*model.ResumesProject, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resumesProjectDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resumesProjectDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resumesProjectDo) Delete(models ...*model.ResumesProject) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resumesProjectDo) withDO(do gen.Dao) *resumesProjectDo {
	r.DO = *do.(*gen.DO)
	return r
}
