// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"module.resume/internal/infrastructure/persistence/gorm/model"
)

func newResumesCoverLetter(db *gorm.DB, opts ...gen.DOOption) resumesCoverLetter {
	_resumesCoverLetter := resumesCoverLetter{}

	_resumesCoverLetter.resumesCoverLetterDo.UseDB(db, opts...)
	_resumesCoverLetter.resumesCoverLetterDo.UseModel(&model.ResumesCoverLetter{})

	tableName := _resumesCoverLetter.resumesCoverLetterDo.TableName()
	_resumesCoverLetter.ALL = field.NewAsterisk(tableName)
	_resumesCoverLetter.ResumesID = field.NewInt64(tableName, "resumes_id")
	_resumesCoverLetter.CoverLettersID = field.NewInt64(tableName, "cover_letters_id")

	_resumesCoverLetter.fillFieldMap()

	return _resumesCoverLetter
}

type resumesCoverLetter struct {
	resumesCoverLetterDo resumesCoverLetterDo

	ALL            field.Asterisk
	ResumesID      field.Int64
	CoverLettersID field.Int64

	fieldMap map[string]field.Expr
}

func (r resumesCoverLetter) Table(newTableName string) *resumesCoverLetter {
	r.resumesCoverLetterDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resumesCoverLetter) As(alias string) *resumesCoverLetter {
	r.resumesCoverLetterDo.DO = *(r.resumesCoverLetterDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resumesCoverLetter) updateTableName(table string) *resumesCoverLetter {
	r.ALL = field.NewAsterisk(table)
	r.ResumesID = field.NewInt64(table, "resumes_id")
	r.CoverLettersID = field.NewInt64(table, "cover_letters_id")

	r.fillFieldMap()

	return r
}

func (r *resumesCoverLetter) WithContext(ctx context.Context) *resumesCoverLetterDo {
	return r.resumesCoverLetterDo.WithContext(ctx)
}

func (r resumesCoverLetter) TableName() string { return r.resumesCoverLetterDo.TableName() }

func (r resumesCoverLetter) Alias() string { return r.resumesCoverLetterDo.Alias() }

func (r resumesCoverLetter) Columns(cols ...field.Expr) gen.Columns {
	return r.resumesCoverLetterDo.Columns(cols...)
}

func (r *resumesCoverLetter) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resumesCoverLetter) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 2)
	r.fieldMap["resumes_id"] = r.ResumesID
	r.fieldMap["cover_letters_id"] = r.CoverLettersID
}

func (r resumesCoverLetter) clone(db *gorm.DB) resumesCoverLetter {
	r.resumesCoverLetterDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resumesCoverLetter) replaceDB(db *gorm.DB) resumesCoverLetter {
	r.resumesCoverLetterDo.ReplaceDB(db)
	return r
}

type resumesCoverLetterDo struct{ gen.DO }

func (r resumesCoverLetterDo) Debug() *resumesCoverLetterDo {
	return r.withDO(r.DO.Debug())
}

func (r resumesCoverLetterDo) WithContext(ctx context.Context) *resumesCoverLetterDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resumesCoverLetterDo) ReadDB() *resumesCoverLetterDo {
	return r.Clauses(dbresolver.Read)
}

func (r resumesCoverLetterDo) WriteDB() *resumesCoverLetterDo {
	return r.Clauses(dbresolver.Write)
}

func (r resumesCoverLetterDo) Session(config *gorm.Session) *resumesCoverLetterDo {
	return r.withDO(r.DO.Session(config))
}

func (r resumesCoverLetterDo) Clauses(conds ...clause.Expression) *resumesCoverLetterDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resumesCoverLetterDo) Returning(value interface{}, columns ...string) *resumesCoverLetterDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resumesCoverLetterDo) Not(conds ...gen.Condition) *resumesCoverLetterDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resumesCoverLetterDo) Or(conds ...gen.Condition) *resumesCoverLetterDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resumesCoverLetterDo) Select(conds ...field.Expr) *resumesCoverLetterDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resumesCoverLetterDo) Where(conds ...gen.Condition) *resumesCoverLetterDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resumesCoverLetterDo) Order(conds ...field.Expr) *resumesCoverLetterDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resumesCoverLetterDo) Distinct(cols ...field.Expr) *resumesCoverLetterDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resumesCoverLetterDo) Omit(cols ...field.Expr) *resumesCoverLetterDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resumesCoverLetterDo) Join(table schema.Tabler, on ...field.Expr) *resumesCoverLetterDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resumesCoverLetterDo) LeftJoin(table schema.Tabler, on ...field.Expr) *resumesCoverLetterDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resumesCoverLetterDo) RightJoin(table schema.Tabler, on ...field.Expr) *resumesCoverLetterDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resumesCoverLetterDo) Group(cols ...field.Expr) *resumesCoverLetterDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resumesCoverLetterDo) Having(conds ...gen.Condition) *resumesCoverLetterDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resumesCoverLetterDo) Limit(limit int) *resumesCoverLetterDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resumesCoverLetterDo) Offset(offset int) *resumesCoverLetterDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resumesCoverLetterDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *resumesCoverLetterDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resumesCoverLetterDo) Unscoped() *resumesCoverLetterDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resumesCoverLetterDo) Create(values ...*model.ResumesCoverLetter) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resumesCoverLetterDo) CreateInBatches(values []*model.ResumesCoverLetter, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resumesCoverLetterDo) Save(values ...*model.ResumesCoverLetter) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resumesCoverLetterDo) First() (*model.ResumesCoverLetter, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesCoverLetter), nil
	}
}

func (r resumesCoverLetterDo) Take() (*model.ResumesCoverLetter, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesCoverLetter), nil
	}
}

func (r resumesCoverLetterDo) Last() (*model.ResumesCoverLetter, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesCoverLetter), nil
	}
}

func (r resumesCoverLetterDo) Find() ([]*model.ResumesCoverLetter, error) {
	result, err := r.DO.Find()
	return result.([]*model.ResumesCoverLetter), err
}

func (r resumesCoverLetterDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResumesCoverLetter, err error) {
	buf := make([]*model.ResumesCoverLetter, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resumesCoverLetterDo) FindInBatches(result *[]*model.ResumesCoverLetter, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resumesCoverLetterDo) Attrs(attrs ...field.AssignExpr) *resumesCoverLetterDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resumesCoverLetterDo) Assign(attrs ...field.AssignExpr) *resumesCoverLetterDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resumesCoverLetterDo) Joins(fields ...field.RelationField) *resumesCoverLetterDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resumesCoverLetterDo) Preload(fields ...field.RelationField) *resumesCoverLetterDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resumesCoverLetterDo) FirstOrInit() (*model.ResumesCoverLetter, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesCoverLetter), nil
	}
}

func (r resumesCoverLetterDo) FirstOrCreate() (*model.ResumesCoverLetter, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesCoverLetter), nil
	}
}

func (r resumesCoverLetterDo) FindByPage(offset int, limit int) (result []*model.ResumesCoverLetter, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resumesCoverLetterDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resumesCoverLetterDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resumesCoverLetterDo) Delete(models ...*model.ResumesCoverLetter) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resumesCoverLetterDo) withDO(do gen.Dao) *resumesCoverLetterDo {
	r.DO = *do.(*gen.DO)
	return r
}
