// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"module.resume/internal/infrastructure/persistence/gorm/model"
)

func newResumesAward(db *gorm.DB, opts ...gen.DOOption) resumesAward {
	_resumesAward := resumesAward{}

	_resumesAward.resumesAwardDo.UseDB(db, opts...)
	_resumesAward.resumesAwardDo.UseModel(&model.ResumesAward{})

	tableName := _resumesAward.resumesAwardDo.TableName()
	_resumesAward.ALL = field.NewAsterisk(tableName)
	_resumesAward.ResumesID = field.NewInt64(tableName, "resumes_id")
	_resumesAward.AwardsID = field.NewInt64(tableName, "awards_id")
	_resumesAward.Order = field.NewInt32(tableName, "order")
	_resumesAward.PrivateMemo = field.NewString(tableName, "private_memo")

	_resumesAward.fillFieldMap()

	return _resumesAward
}

type resumesAward struct {
	resumesAwardDo resumesAwardDo

	ALL         field.Asterisk
	ResumesID   field.Int64
	AwardsID    field.Int64
	Order       field.Int32
	PrivateMemo field.String

	fieldMap map[string]field.Expr
}

func (r resumesAward) Table(newTableName string) *resumesAward {
	r.resumesAwardDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resumesAward) As(alias string) *resumesAward {
	r.resumesAwardDo.DO = *(r.resumesAwardDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resumesAward) updateTableName(table string) *resumesAward {
	r.ALL = field.NewAsterisk(table)
	r.ResumesID = field.NewInt64(table, "resumes_id")
	r.AwardsID = field.NewInt64(table, "awards_id")
	r.Order = field.NewInt32(table, "order")
	r.PrivateMemo = field.NewString(table, "private_memo")

	r.fillFieldMap()

	return r
}

func (r *resumesAward) WithContext(ctx context.Context) *resumesAwardDo {
	return r.resumesAwardDo.WithContext(ctx)
}

func (r resumesAward) TableName() string { return r.resumesAwardDo.TableName() }

func (r resumesAward) Alias() string { return r.resumesAwardDo.Alias() }

func (r resumesAward) Columns(cols ...field.Expr) gen.Columns {
	return r.resumesAwardDo.Columns(cols...)
}

func (r *resumesAward) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resumesAward) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 4)
	r.fieldMap["resumes_id"] = r.ResumesID
	r.fieldMap["awards_id"] = r.AwardsID
	r.fieldMap["order"] = r.Order
	r.fieldMap["private_memo"] = r.PrivateMemo
}

func (r resumesAward) clone(db *gorm.DB) resumesAward {
	r.resumesAwardDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resumesAward) replaceDB(db *gorm.DB) resumesAward {
	r.resumesAwardDo.ReplaceDB(db)
	return r
}

type resumesAwardDo struct{ gen.DO }

func (r resumesAwardDo) Debug() *resumesAwardDo {
	return r.withDO(r.DO.Debug())
}

func (r resumesAwardDo) WithContext(ctx context.Context) *resumesAwardDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resumesAwardDo) ReadDB() *resumesAwardDo {
	return r.Clauses(dbresolver.Read)
}

func (r resumesAwardDo) WriteDB() *resumesAwardDo {
	return r.Clauses(dbresolver.Write)
}

func (r resumesAwardDo) Session(config *gorm.Session) *resumesAwardDo {
	return r.withDO(r.DO.Session(config))
}

func (r resumesAwardDo) Clauses(conds ...clause.Expression) *resumesAwardDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resumesAwardDo) Returning(value interface{}, columns ...string) *resumesAwardDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resumesAwardDo) Not(conds ...gen.Condition) *resumesAwardDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resumesAwardDo) Or(conds ...gen.Condition) *resumesAwardDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resumesAwardDo) Select(conds ...field.Expr) *resumesAwardDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resumesAwardDo) Where(conds ...gen.Condition) *resumesAwardDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resumesAwardDo) Order(conds ...field.Expr) *resumesAwardDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resumesAwardDo) Distinct(cols ...field.Expr) *resumesAwardDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resumesAwardDo) Omit(cols ...field.Expr) *resumesAwardDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resumesAwardDo) Join(table schema.Tabler, on ...field.Expr) *resumesAwardDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resumesAwardDo) LeftJoin(table schema.Tabler, on ...field.Expr) *resumesAwardDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resumesAwardDo) RightJoin(table schema.Tabler, on ...field.Expr) *resumesAwardDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resumesAwardDo) Group(cols ...field.Expr) *resumesAwardDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resumesAwardDo) Having(conds ...gen.Condition) *resumesAwardDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resumesAwardDo) Limit(limit int) *resumesAwardDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resumesAwardDo) Offset(offset int) *resumesAwardDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resumesAwardDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *resumesAwardDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resumesAwardDo) Unscoped() *resumesAwardDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resumesAwardDo) Create(values ...*model.ResumesAward) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resumesAwardDo) CreateInBatches(values []*model.ResumesAward, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resumesAwardDo) Save(values ...*model.ResumesAward) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resumesAwardDo) First() (*model.ResumesAward, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesAward), nil
	}
}

func (r resumesAwardDo) Take() (*model.ResumesAward, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesAward), nil
	}
}

func (r resumesAwardDo) Last() (*model.ResumesAward, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesAward), nil
	}
}

func (r resumesAwardDo) Find() ([]*model.ResumesAward, error) {
	result, err := r.DO.Find()
	return result.([]*model.ResumesAward), err
}

func (r resumesAwardDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResumesAward, err error) {
	buf := make([]*model.ResumesAward, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resumesAwardDo) FindInBatches(result *[]*model.ResumesAward, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resumesAwardDo) Attrs(attrs ...field.AssignExpr) *resumesAwardDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resumesAwardDo) Assign(attrs ...field.AssignExpr) *resumesAwardDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resumesAwardDo) Joins(fields ...field.RelationField) *resumesAwardDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resumesAwardDo) Preload(fields ...field.RelationField) *resumesAwardDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resumesAwardDo) FirstOrInit() (*model.ResumesAward, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesAward), nil
	}
}

func (r resumesAwardDo) FirstOrCreate() (*model.ResumesAward, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesAward), nil
	}
}

func (r resumesAwardDo) FindByPage(offset int, limit int) (result []*model.ResumesAward, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resumesAwardDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resumesAwardDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resumesAwardDo) Delete(models ...*model.ResumesAward) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resumesAwardDo) withDO(do gen.Dao) *resumesAwardDo {
	r.DO = *do.(*gen.DO)
	return r
}
