// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"module.resume/internal/infrastructure/persistence/gorm/model"
)

func newResumesEducation(db *gorm.DB, opts ...gen.DOOption) resumesEducation {
	_resumesEducation := resumesEducation{}

	_resumesEducation.resumesEducationDo.UseDB(db, opts...)
	_resumesEducation.resumesEducationDo.UseModel(&model.ResumesEducation{})

	tableName := _resumesEducation.resumesEducationDo.TableName()
	_resumesEducation.ALL = field.NewAsterisk(tableName)
	_resumesEducation.ResumesID = field.NewInt64(tableName, "resumes_id")
	_resumesEducation.EducationsID = field.NewInt64(tableName, "educations_id")
	_resumesEducation.Order = field.NewInt32(tableName, "order")
	_resumesEducation.PrivateMemo = field.NewString(tableName, "private_memo")

	_resumesEducation.fillFieldMap()

	return _resumesEducation
}

type resumesEducation struct {
	resumesEducationDo resumesEducationDo

	ALL          field.Asterisk
	ResumesID    field.Int64
	EducationsID field.Int64
	Order        field.Int32
	PrivateMemo  field.String

	fieldMap map[string]field.Expr
}

func (r resumesEducation) Table(newTableName string) *resumesEducation {
	r.resumesEducationDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resumesEducation) As(alias string) *resumesEducation {
	r.resumesEducationDo.DO = *(r.resumesEducationDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resumesEducation) updateTableName(table string) *resumesEducation {
	r.ALL = field.NewAsterisk(table)
	r.ResumesID = field.NewInt64(table, "resumes_id")
	r.EducationsID = field.NewInt64(table, "educations_id")
	r.Order = field.NewInt32(table, "order")
	r.PrivateMemo = field.NewString(table, "private_memo")

	r.fillFieldMap()

	return r
}

func (r *resumesEducation) WithContext(ctx context.Context) *resumesEducationDo {
	return r.resumesEducationDo.WithContext(ctx)
}

func (r resumesEducation) TableName() string { return r.resumesEducationDo.TableName() }

func (r resumesEducation) Alias() string { return r.resumesEducationDo.Alias() }

func (r resumesEducation) Columns(cols ...field.Expr) gen.Columns {
	return r.resumesEducationDo.Columns(cols...)
}

func (r *resumesEducation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resumesEducation) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 4)
	r.fieldMap["resumes_id"] = r.ResumesID
	r.fieldMap["educations_id"] = r.EducationsID
	r.fieldMap["order"] = r.Order
	r.fieldMap["private_memo"] = r.PrivateMemo
}

func (r resumesEducation) clone(db *gorm.DB) resumesEducation {
	r.resumesEducationDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resumesEducation) replaceDB(db *gorm.DB) resumesEducation {
	r.resumesEducationDo.ReplaceDB(db)
	return r
}

type resumesEducationDo struct{ gen.DO }

func (r resumesEducationDo) Debug() *resumesEducationDo {
	return r.withDO(r.DO.Debug())
}

func (r resumesEducationDo) WithContext(ctx context.Context) *resumesEducationDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resumesEducationDo) ReadDB() *resumesEducationDo {
	return r.Clauses(dbresolver.Read)
}

func (r resumesEducationDo) WriteDB() *resumesEducationDo {
	return r.Clauses(dbresolver.Write)
}

func (r resumesEducationDo) Session(config *gorm.Session) *resumesEducationDo {
	return r.withDO(r.DO.Session(config))
}

func (r resumesEducationDo) Clauses(conds ...clause.Expression) *resumesEducationDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resumesEducationDo) Returning(value interface{}, columns ...string) *resumesEducationDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resumesEducationDo) Not(conds ...gen.Condition) *resumesEducationDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resumesEducationDo) Or(conds ...gen.Condition) *resumesEducationDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resumesEducationDo) Select(conds ...field.Expr) *resumesEducationDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resumesEducationDo) Where(conds ...gen.Condition) *resumesEducationDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resumesEducationDo) Order(conds ...field.Expr) *resumesEducationDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resumesEducationDo) Distinct(cols ...field.Expr) *resumesEducationDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resumesEducationDo) Omit(cols ...field.Expr) *resumesEducationDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resumesEducationDo) Join(table schema.Tabler, on ...field.Expr) *resumesEducationDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resumesEducationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *resumesEducationDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resumesEducationDo) RightJoin(table schema.Tabler, on ...field.Expr) *resumesEducationDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resumesEducationDo) Group(cols ...field.Expr) *resumesEducationDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resumesEducationDo) Having(conds ...gen.Condition) *resumesEducationDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resumesEducationDo) Limit(limit int) *resumesEducationDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resumesEducationDo) Offset(offset int) *resumesEducationDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resumesEducationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *resumesEducationDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resumesEducationDo) Unscoped() *resumesEducationDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resumesEducationDo) Create(values ...*model.ResumesEducation) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resumesEducationDo) CreateInBatches(values []*model.ResumesEducation, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resumesEducationDo) Save(values ...*model.ResumesEducation) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resumesEducationDo) First() (*model.ResumesEducation, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesEducation), nil
	}
}

func (r resumesEducationDo) Take() (*model.ResumesEducation, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesEducation), nil
	}
}

func (r resumesEducationDo) Last() (*model.ResumesEducation, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesEducation), nil
	}
}

func (r resumesEducationDo) Find() ([]*model.ResumesEducation, error) {
	result, err := r.DO.Find()
	return result.([]*model.ResumesEducation), err
}

func (r resumesEducationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResumesEducation, err error) {
	buf := make([]*model.ResumesEducation, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resumesEducationDo) FindInBatches(result *[]*model.ResumesEducation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resumesEducationDo) Attrs(attrs ...field.AssignExpr) *resumesEducationDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resumesEducationDo) Assign(attrs ...field.AssignExpr) *resumesEducationDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resumesEducationDo) Joins(fields ...field.RelationField) *resumesEducationDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resumesEducationDo) Preload(fields ...field.RelationField) *resumesEducationDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resumesEducationDo) FirstOrInit() (*model.ResumesEducation, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesEducation), nil
	}
}

func (r resumesEducationDo) FirstOrCreate() (*model.ResumesEducation, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumesEducation), nil
	}
}

func (r resumesEducationDo) FindByPage(offset int, limit int) (result []*model.ResumesEducation, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resumesEducationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resumesEducationDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resumesEducationDo) Delete(models ...*model.ResumesEducation) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resumesEducationDo) withDO(do gen.Dao) *resumesEducationDo {
	r.DO = *do.(*gen.DO)
	return r
}
