// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAward = "awards"

// Award mapped from table <awards>
type Award struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UsersID     int64          `gorm:"column:users_id;not null" json:"users_id"`
	Name        string         `gorm:"column:name;not null" json:"name"`
	Issuer      string         `gorm:"column:issuer" json:"issuer"`
	AwardedDate time.Time      `gorm:"column:awarded_date;not null" json:"awarded_date"`
	Description string         `gorm:"column:description" json:"description"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Award's table name
func (*Award) TableName() string {
	return TableNameAward
}
