// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCertificate = "certificates"

// Certificate mapped from table <certificates>
type Certificate struct {
	ID             int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UsersID        int64          `gorm:"column:users_id;not null" json:"users_id"`
	Name           string         `gorm:"column:name;not null" json:"name"`
	IssuedBy       string         `gorm:"column:issued_by;not null" json:"issued_by"`
	IssuedDate     time.Time      `gorm:"column:issued_date;not null" json:"issued_date"`
	ExpirationDate time.Time      `gorm:"column:expiration_date" json:"expiration_date"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Certificate's table name
func (*Certificate) TableName() string {
	return TableNameCertificate
}
