// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameCommonType = "common_types"

// CommonType mapped from table <common_types>
type CommonType struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Domain      string         `gorm:"column:domain;not null" json:"domain"`
	Code        string         `gorm:"column:code;not null" json:"code"`
	Name        string         `gorm:"column:name;not null" json:"name"`
	Description string         `gorm:"column:description" json:"description"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName CommonType's table name
func (*CommonType) TableName() string {
	return TableNameCommonType
}
