// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameCoverLetter = "cover_letters"

// CoverLetter mapped from table <cover_letters>
type CoverLetter struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UsersID   int64          `gorm:"column:users_id;not null" json:"users_id"`
	Title     string         `gorm:"column:title" json:"title"`
	Content   string         `gorm:"column:content;not null" json:"content"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName CoverLetter's table name
func (*CoverLetter) TableName() string {
	return TableNameCoverLetter
}
