// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDiary = "diaries"

// Diary mapped from table <diaries>
type Diary struct {
	ID                int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UsersID           int64          `gorm:"column:users_id;not null" json:"users_id"`
	WorkExperiencesID int64          `gorm:"column:work_experiences_id" json:"work_experiences_id"`
	TypesID           int64          `gorm:"column:types_id" json:"types_id"`
	ProjectsID        int64          `gorm:"column:projects_id" json:"projects_id"`
	Content           string         `gorm:"column:content;not null" json:"content"`
	Mood              string         `gorm:"column:mood" json:"mood"`
	CreatedAt         time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt         time.Time      `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Diary's table name
func (*Diary) TableName() string {
	return TableNameDiary
}
