// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameEducation = "educations"

// Education mapped from table <educations>
type Education struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UsersID     int64          `gorm:"column:users_id;not null" json:"users_id"`
	SchoolName  string         `gorm:"column:school_name;not null" json:"school_name"`
	Major       string         `gorm:"column:major" json:"major"`
	Degree      string         `gorm:"column:degree" json:"degree"`
	StartDate   time.Time      `gorm:"column:start_date;not null" json:"start_date"`
	EndDate     time.Time      `gorm:"column:end_date;not null" json:"end_date"`
	Description string         `gorm:"column:description" json:"description"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Education's table name
func (*Education) TableName() string {
	return TableNameEducation
}
