// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameLink = "links"

// Link mapped from table <links>
type Link struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UsersID   int64          `gorm:"column:users_id;not null" json:"users_id"`
	URL       string         `gorm:"column:url;not null" json:"url"`
	Label     string         `gorm:"column:label;not null" json:"label"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Link's table name
func (*Link) TableName() string {
	return TableNameLink
}
