// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameProject = "projects"

// Project mapped from table <projects>
type Project struct {
	ID                int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UsersID           int64          `gorm:"column:users_id;not null" json:"users_id"`
	WorkExperiencesID int64          `gorm:"column:work_experiences_id" json:"work_experiences_id"`
	Title             string         `gorm:"column:title;not null" json:"title"`
	Description       string         `gorm:"column:description" json:"description"`
	Role              string         `gorm:"column:role" json:"role"`
	StartDate         time.Time      `gorm:"column:start_date;not null" json:"start_date"`
	EndDate           time.Time      `gorm:"column:end_date" json:"end_date"`
	CreatedAt         time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt         time.Time      `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
