// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameResumesCoverLetter = "resumes_cover_letters"

// ResumesCoverLetter mapped from table <resumes_cover_letters>
type ResumesCoverLetter struct {
	ResumesID      int64 `gorm:"column:resumes_id;primaryKey" json:"resumes_id"`
	CoverLettersID int64 `gorm:"column:cover_letters_id;primaryKey" json:"cover_letters_id"`
}

// TableName ResumesCoverLetter's table name
func (*ResumesCoverLetter) TableName() string {
	return TableNameResumesCoverLetter
}
