// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameResumesSkill = "resumes_skills"

// ResumesSkill mapped from table <resumes_skills>
type ResumesSkill struct {
	ResumesID   int64  `gorm:"column:resumes_id;primaryKey" json:"resumes_id"`
	SkillsID    int64  `gorm:"column:skills_id;primaryKey" json:"skills_id"`
	Order       int32  `gorm:"column:order" json:"order"`
	PrivateMemo string `gorm:"column:private_memo" json:"private_memo"`
}

// TableName ResumesSkill's table name
func (*ResumesSkill) TableName() string {
	return TableNameResumesSkill
}
