// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameResumesCertificate = "resumes_certificates"

// ResumesCertificate mapped from table <resumes_certificates>
type ResumesCertificate struct {
	ResumesID      int64  `gorm:"column:resumes_id;primaryKey" json:"resumes_id"`
	CertificatesID int64  `gorm:"column:certificates_id;primaryKey" json:"certificates_id"`
	Order          int32  `gorm:"column:order;not null" json:"order"`
	PrivateMemo    string `gorm:"column:private_memo" json:"private_memo"`
}

// TableName ResumesCertificate's table name
func (*ResumesCertificate) TableName() string {
	return TableNameResumesCertificate
}
