// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameResumesLink = "resumes_links"

// ResumesLink mapped from table <resumes_links>
type ResumesLink struct {
	ResumesID int64 `gorm:"column:resumes_id;primaryKey" json:"resumes_id"`
	LinksID   int64 `gorm:"column:links_id;primaryKey" json:"links_id"`
}

// TableName ResumesLink's table name
func (*ResumesLink) TableName() string {
	return TableNameResumesLink
}
