// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameResumesAward = "resumes_awards"

// ResumesAward mapped from table <resumes_awards>
type ResumesAward struct {
	ResumesID   int64  `gorm:"column:resumes_id;primaryKey" json:"resumes_id"`
	AwardsID    int64  `gorm:"column:awards_id;primaryKey" json:"awards_id"`
	Order       int32  `gorm:"column:order;not null" json:"order"`
	PrivateMemo string `gorm:"column:private_memo" json:"private_memo"`
}

// TableName ResumesAward's table name
func (*ResumesAward) TableName() string {
	return TableNameResumesAward
}
