// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameResumesWorkExperience = "resumes_work_experiences"

// ResumesWorkExperience mapped from table <resumes_work_experiences>
type ResumesWorkExperience struct {
	ResumesID         int64  `gorm:"column:resumes_id;primaryKey" json:"resumes_id"`
	WorkExperiencesID int64  `gorm:"column:work_experiences_id;primaryKey" json:"work_experiences_id"`
	Order             int32  `gorm:"column:order;not null" json:"order"`
	PrivateNote       string `gorm:"column:private_note" json:"private_note"`
}

// TableName ResumesWorkExperience's table name
func (*ResumesWorkExperience) TableName() string {
	return TableNameResumesWorkExperience
}
