// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameResumesEducation = "resumes_educations"

// ResumesEducation mapped from table <resumes_educations>
type ResumesEducation struct {
	ResumesID    int64  `gorm:"column:resumes_id;primaryKey" json:"resumes_id"`
	EducationsID int64  `gorm:"column:educations_id;primaryKey" json:"educations_id"`
	Order        int32  `gorm:"column:order;not null" json:"order"`
	PrivateMemo  string `gorm:"column:private_memo" json:"private_memo"`
}

// TableName ResumesEducation's table name
func (*ResumesEducation) TableName() string {
	return TableNameResumesEducation
}
