// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameResumesProject = "resumes_projects"

// ResumesProject mapped from table <resumes_projects>
type ResumesProject struct {
	ResumesID   int64  `gorm:"column:resumes_id;primaryKey" json:"resumes_id"`
	ProjectsID  int64  `gorm:"column:projects_id;primaryKey" json:"projects_id"`
	Order       int32  `gorm:"column:order;not null" json:"order"`
	PrivateNote string `gorm:"column:private_note" json:"private_note"`
}

// TableName ResumesProject's table name
func (*ResumesProject) TableName() string {
	return TableNameResumesProject
}
