// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameSkill = "skills"

// Skill mapped from table <skills>
type Skill struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UsersID   int64          `gorm:"column:users_id;not null" json:"users_id"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	Level     string         `gorm:"column:level" json:"level"`
	Category  string         `gorm:"column:category" json:"category"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Skill's table name
func (*Skill) TableName() string {
	return TableNameSkill
}
