// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameWorkExperience = "work_experiences"

// WorkExperience mapped from table <work_experiences>
type WorkExperience struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UsersID     int64          `gorm:"column:users_id;not null" json:"users_id"`
	CompaniesID int64          `gorm:"column:companies_id;not null" json:"companies_id"`
	Role        string         `gorm:"column:role" json:"role"`
	StartDate   time.Time      `gorm:"column:start_date;not null" json:"start_date"`
	EndDate     time.Time      `gorm:"column:end_date" json:"end_date"`
	Description string         `gorm:"column:description" json:"description"`
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName WorkExperience's table name
func (*WorkExperience) TableName() string {
	return TableNameWorkExperience
}
